### ISSUE TITLE
Unable to run manage.py on a project using version 8.4

### ISSUE THREAD

**Issue by riclima** [django-danceschool/django-danceschool#139] opened 2019-04-02 22:27 UTC
Steps to reproduce:

1. Start a new project with version 8.4
2. Run manage.py

Been debugging for the past few hours but I can't seem to figure out why this happens:

```
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "django_content_type" does not exist
LINE 1: ..."."app_label", "django_content_type"."model" FROM "django_co...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/vagrant/django-danceschool/danceschool/discounts/apps.py", line 10, in ready
    from . import handlers
  File "/vagrant/django-danceschool/danceschool/discounts/handlers.py", line 11, in <module>
    from danceschool.core.classreg import RegistrationSummaryView
  File "/vagrant/django-danceschool/danceschool/core/classreg.py", line 18, in <module>
    from .forms import ClassChoiceForm, RegistrationContactForm, DoorAmountForm
  File "/vagrant/django-danceschool/danceschool/core/forms.py", line 588, in <module>
    class EventAutocompleteForm(forms.Form):
  File "/vagrant/django-danceschool/danceschool/core/forms.py", line 595, in EventAutocompleteForm
    queryset=Event.objects.filter(Q(instance_of=PublicEvent) | Q(instance_of=Series)),
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/models/query.py", line 787, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/vagrant/venv/lib/python3.5/site-packages/polymorphic/query.py", line 155, in _filter_or_exclude
    q_objects = translate_polymorphic_filter_definitions_in_args(self.model, args, using=self.db)  # the Q objects
  File "/home/vagrant/venv/lib/python3.5/site-packages/polymorphic/query_translate.py", line 90, in translate_polymorphic_filter_definitions_in_args
    return [translate_polymorphic_Q_object(queryset_model, copy.deepcopy(q), using=using) for q in args]
  File "/home/vagrant/venv/lib/python3.5/site-packages/polymorphic/query_translate.py", line 90, in <listcomp>
    return [translate_polymorphic_Q_object(queryset_model, copy.deepcopy(q), using=using) for q in args]
  File "/home/vagrant/venv/lib/python3.5/site-packages/polymorphic/query_translate.py", line 74, in translate_polymorphic_Q_object
    tree_node_correct_field_specs(queryset_model, potential_q_object)
  File "/home/vagrant/venv/lib/python3.5/site-packages/polymorphic/query_translate.py", line 66, in tree_node_correct_field_specs
    new_expr = _translate_polymorphic_filter_definition(my_model, key, val, using=using)
  File "/home/vagrant/venv/lib/python3.5/site-packages/polymorphic/query_translate.py", line 108, in _translate_polymorphic_filter_definition
    return _create_model_filter_Q(field_val, using=using)
  File "/home/vagrant/venv/lib/python3.5/site-packages/polymorphic/query_translate.py", line 247, in _create_model_filter_Q
    qlist = [q_class_with_subclasses(m) for m in modellist]
  File "/home/vagrant/venv/lib/python3.5/site-packages/polymorphic/query_translate.py", line 247, in <listcomp>
    qlist = [q_class_with_subclasses(m) for m in modellist]
  File "/home/vagrant/venv/lib/python3.5/site-packages/polymorphic/query_translate.py", line 242, in q_class_with_subclasses
    q = models.Q(polymorphic_ctype=ContentType.objects.db_manager(using).get_for_model(model, for_concrete_model=False))
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/contrib/contenttypes/models.py", line 54, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/vagrant/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_content_type" does not exist
LINE 1: ..."."app_label", "django_content_type"."model" FROM "django_co...
```
If I rollback to 8.3, no problems. Looks like something is trying to access database data before it is migrated, causing the error.

**Comment by riclima** [comment] 2019-04-02 23:43
I've identified the commit that causes the issue: https://github.com/django-danceschool/django-danceschool/commit/d774083d7754cc09eabdb68a5d8ce799ed412a42

Specifically, the error is raised here: https://github.com/django-danceschool/django-danceschool/commit/d774083d7754cc09eabdb68a5d8ce799ed412a42#diff-4b603875869ca5093e4db6f0bd7c5945R588

Not sure why that happens, but my guess is that the application is attempting to access the database before it is setup, and so it crashes. I've reverted that specific commit on my fork and it seems to work now.

**Comment by leetucker** [comment] 2019-04-03 02:43
@riclima Thanks for identifying the commit at issue so quickly!  I'm going to try to replicate this.  Are you using the development-template repo to start the project, or is there anything else about your project-specific setup that you think I need to know before I dive in?

**Comment by riclima** [comment] 2019-04-03 02:47
I ran on the issue when updating my development environnement, then to make sure it wasn’t an issue with it I reproduced it using the new project template. I don’t know if it’s relevant but the database used was Postgres.

**Comment by leetucker** [comment] 2019-04-03 03:12
OK, I was able to replicate and solve the issue!

The issue is at line 595 of `danceschool/core/forms.py`.  The instance_of filter, which is provided by the django-polymorphic app, seems to be the issue.  So, filtering the queryset to include only Series and PublicEvent subclasses of Event (i.e. excluding private events if the `danceschool.private_events` app is in use) was referencing those content types.

The good news is that there is a logically equivalent way to perform this same filter that works without any issue of referencing content types.  The queryset filter is now:

`Event.objects.filter(Q(publicevent__isnull=False) | Q(series__isnull=False))`

I'll make the commit and close this.

**Comment by riclima** [comment] 2019-04-03 03:14
Great! Thanks for looking at it so quickly.

**Closed** 2019-04-03 03:16 UTC
