### ISSUE TITLE
Unable to scroll down in most pages opened in the sideframe

### ISSUE THREAD

**Issue by riclima** [django-danceschool/django-danceschool#89] opened 2018-03-20 21:08 UTC
I'm in the process of deploying an instance of django-danceschool, and I'm running into a strange bug. For example, if I click on the toolbar Apps > Users… > $some_user, I'm unable to scroll the resulting page inside the sideframe. Many of the pages display the same behaviour.

I've spent a few hours exploring the problem but due to lack of experience with Django CMS, I figured I'd file an issue so I can get more help writing a patch. I'm not sure if it's an upstream problem from Django CMS, but what I found was that there is a CSS class called "cms-prevent-scrolling" applied at the HTML element inside the iframe for the Users page. If I manually remove that class with the inspector, everything works fine. A quick investigation of where the class is being added led me to this file on Django CMS: https://github.com/divio/django-cms/blob/4c0539d2aa5dfb240dfc04207936e05670c19aa0/cms/static/cms/js/modules/cms.sideframe.js#L319

I'm running the latest version of django-danceschool 0.5.2, and django-cms 3.5.1. Let me know what other information I can provide to help debug.

Screenshot:
<img width="1680" alt="screen shot 2018-03-20 at 5 11 34 pm" src="https://user-images.githubusercontent.com/6548873/37683150-032b11a2-2c62-11e8-8aa7-d26cd797dedd.png">

**Comment by leetucker** [comment] 2018-04-27 02:51
This definitely looks like a Django CMS issue.  I have the same issue on our installation of the project.

From a quick look at the Django CMS code base, it looks like the .cms-prevent-scrolling class is added by Javascript when the sideframe is loaded.  See static/cms/js/modules/cms.sideframe.js within that app, around lin 316.  It seems like the idea is to encourage touchscreen support, but this has the effect of not working very well on desktop machines.

It's probably not a great idea for this project to override the CMS defaults on this, so the best course of action is probably to submit a patch or at least an issue to the Django CMS team.  Without understanding what the existing code is trying to accomplish though, I'm not sure quite what the patch should be, you may have to talk it through with them.

**Comment by riclima** [comment] 2018-04-27 03:01
Yeah, I had thought it was an upstream problem, but since I’m not very experienced with Django CMS, I figured I’d start here. I did explore the issue a bit later, but didn’t update the issue cause I haven’t found a solution yet. I’m planning on exploring the issue in detail next week. I’ll keep you posted.

**Comment by afs2015** [comment] 2018-05-14 15:29
Hey @riclima, any updates? I'm at PyCon 2018 so i'm hoping to dig into some of the issues on django-danceschool the last two days of the sprints.

**Comment by riclima** [comment] 2018-05-25 21:53
Sorry, I didn’t quite have as much time last few weeks—much of my free time was spent preparing for an InfoSec conference/CTF that happened last week. I’ll see if I can investigate it this weekend, but I’ve got a backlog of IT tasks for our studio that might take up all my time. I’ll keep you posted! I hope you enjoyed PyCon!

**Comment by leetucker** [comment] 2018-09-01 17:50
OK, I did some substantial investigation of this problem, and unfortunately it turns out that it is not a bug in those other projects, but a function of the way in which we are overriding the `admin/base.html` template.  Basically, we want the non-sideframe admin pages to have the same dropdown menus showing as front-end pages, and in order to do that we load the needed Javascript in `admin/base.html`.  But this load the Javascript from the static file `cms/js/modules/cms.sideframe.js`, which adds the cms-prevent-scrolling class to `<body>` without checking to see if the page is in an iframe (i.e. if it is a sideframe).

The problem is that we can't just override `cms/js/modules/cms.sideframe.js`, because it isn't actually loaded; Django CMS uses Webpack to distribute the minified code as `cms/static/cms/js/dist/<version>/bundle.toolbar.min.js`.  In order to fix the problem that way, we would have to modify the bundled file, and the path to that file changes with each revision of Django CMS, so that seems pretty undesirable.

The alternative solution that I'm working on is to add Javascript to `admin/base.html` that checks to see if the page is inside an iframe, and then adds CSS that overrides the `.cms-prevent-scrolling` class.  I just haven't figured out the correct Javascript event to hook into (checking on `$(document).ready()` doesn't seem to cut it).  If anyone with more advanced JS knowledge than me has suggestions, I'm happy to hear them.

This is a pretty annoying bug, so I'm going to try to fix it ASAP in preparation for the 0.6.0 release.

**Comment by leetucker** [comment] 2018-09-09 19:15
This is fixed in the 0.6.0 release.

**Closed by leetucker** 2018-09-09 19:15 UTC

**Comment by riclima** [comment] 2018-09-21 18:07
Hey! Thanks for fixing the bug. I ended up not having the time to work on this project at all for quite a while, as I've been quite busy with a new job.

**Comment by JonBendtsen** [comment] 2023-08-08 18:33
I seem to be hit by this after using https://github.com/django-danceschool/production-template/tree/master to do a new installation.

How do I see which version of school I am using?

**Comment by JonBendtsen** [comment] 2023-08-08 18:52
pip list

```
Package                           Version
--------------------------------- ------------
arabic-reshaper                   3.0.0
asgiref                           3.7.2
asn1crypto                        1.5.1
async-timeout                     4.0.2
beautifulsoup4                    4.12.2
boto3                             1.28.21
botocore                          1.31.21
certifi                           2023.7.22
cffi                              1.15.1
charset-normalizer                3.2.0
click                             8.1.6
cryptography                      41.0.3
cssselect2                        0.7.0
defusedxml                        0.7.1
dj-database-url                   0.5.0
dj-email-url                      1.0.6
Django                            3.1.14
django-addanother                 2.2.2
django-admin-rangefilter          0.10.0
django-admin-sortable2            1.0.4
django-allauth                    0.54.0
django-appconf                    1.0.5
django-autocomplete-light         3.9.4
django-braces                     1.15.0
django-ckeditor                   6.3.2
django-ckeditor-filebrowser-filer 0.4.0
django-classy-tags                3.0.1
django-cms                        3.11.3
django-colorful                   1.3
django-crispy-forms               1.14.0
django-danceschool                0.9.3
django-dynamic-preferences        1.13.0
django-easy-pdf                   0.1.1
django-filer                      3.0.3
django-formtools                  2.4
django-ical                       1.8.3
django-imagekit                   4.1.0
django-js-asset                   2.0.0
django-multiselectfield           0.1.12
django-polymorphic                3.1.0
django-recurrence                 1.11.1
django-redis                      5.2.0
django-sekizai                    3.0.1
django-storages                   1.12.3
django-treebeard                  4.5.1
django-utils-six                  2.0
djangocms-admin-style             3.2.4
djangocms-attributes-field        3.0.0
djangocms-bootstrap4              3.0.0
djangocms-icon                    2.0.0
djangocms-link                    3.1.1
djangocms-picture                 4.0.0
djangocms-text-ckeditor           5.1.3
easy-thumbnails                   2.8.5
gunicorn                          21.2.0
html5lib                          1.1
huey                              2.4.5
icalendar                         5.0.7
idna                              3.4
intervaltree                      3.1.0
jmespath                          1.0.1
lxml                              4.9.3
oauthlib                          3.2.2
oscrypto                          1.3.0
packaging                         23.1
paypalrestsdk                     1.13.1
peewee                            3.16.2
persisting-theory                 1.0
pilkit                            2.0
Pillow                            10.0.0
pip                               23.2.1
psycopg2-binary                   2.9.7
pycparser                         2.21
pyHanko                           0.20.0
pyhanko-certvalidator             0.23.0
PyJWT                             2.8.0
pyOpenSSL                         23.2.0
pypdf                             3.15.0
pypng                             0.20220715.0
python-bidi                       0.4.2
python-dateutil                   2.8.2
python3-openid                    3.2.0
pytz                              2023.3
PyYAML                            6.0.1
qrcode                            7.4.2
redis                             4.6.0
reportlab                         3.6.13
requests                          2.31.0
requests-oauthlib                 1.3.1
s3transfer                        0.6.1
setuptools                        65.5.1
six                               1.16.0
sortedcontainers                  2.4.0
soupsieve                         2.4.1
sqlparse                          0.4.4
squareconnect                     2.20190724.1
stripe                            5.5.0
svglib                            1.5.1
tinycss2                          1.2.1
typing_extensions                 4.7.1
tzlocal                           5.0.1
unicodecsv                        0.14.1
uritools                          4.0.1
urllib3                           1.26.16
webencodings                      0.5.1
wheel                             0.41.0
whitenoise                        6.5.0
xhtml2pdf                         0.2.11
```

**Comment by JonBendtsen** [comment] 2023-08-08 18:52
@leetucker  can we reopen this?

**Comment by JonBendtsen** [comment] 2023-08-08 19:12
> This definitely looks like a Django CMS issue. I have the same issue on our installation of the project.
> 
> From a quick look at the Django CMS code base, it looks like the .cms-prevent-scrolling class is added by Javascript when the sideframe is loaded. See static/cms/js/modules/cms.sideframe.js within that app, around lin 316. It seems like the idea is to encourage touchscreen support, but this has the effect of not working very well on desktop machines.


Scrollbar is also gone on my iPad Pro, but scrolling does seem to work on my iPhone.
