### ISSUE TITLE
Update template url to the new repo.

### ISSUE THREAD

**Issue by NorthIsUp** [django-danceschool/django-danceschool#66] opened 2017-09-29 23:10 UTC
use `https://github.com/django-danceschool/school-template/archive/master.zip` as the new template url

**Comment by leetucker** [comment] 2017-10-03 20:14
Do we want to have separate template URLs for Heroku/Docker integration vs. local integration?  I'm thinking that all the environment variable stuff that's in this zip file might be intimidating for someone who wants to just set up a simple local install.

Once Heroku integration is ready for others to use, we should update the docs to indicate the installation processes for each.

**Comment by leetucker** [comment] 2018-09-06 23:08
OK, so I've thought about this quite a bit more, and here's the conclusion I've come to.  Even though in principle it is a nice idea to have a single template that can be used for all types of deployments, in practice the `settings.py` file that is used for Heroku and Docker ends up being heavily structured to make use of environment variables, and it is set up for a PostgreSQL backend, and this makes things too difficult for someone who wants to get a quick local install up and running so that they can start tinkering with the code base or developing a custom app.

But, I _also_ think is is the case that the current setup (with the template zip in the `/setup` folder, but in practice always being downloaded from Github directly using `django-admin`) makes little sense.  The reason to download

So, I'm going to create another repo, called "development-template", which will have the contents of `/setup/default_setup.zip` in it.  The documentation for development installations will be updated to make the template URL the URL for this repo.

To avoid confusion, I think that it also makes sense to rename the "school-template" repo to something like "production-template", to make it clear that it is the preferred jumping off point for production deployments using Docker, Heroku, or similar tools.

Soon after the 0.6.0 release, I'm also going to make a couple of Youtube videos which will demonstrate the processes for both production and development installation using the included templates.  I think that this will do a lot to make the process less daunting for users without a lot of experience with these tools.

**Comment by afs2015** [comment] 2018-12-17 16:19
@ADubhlaoich is confirmed this as solved. Marking this as closed.

**Closed by afs2015** 2018-12-17 16:19 UTC
